spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productDb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: amiralaabidi7@gmail.com